# Generated by Django 4.1.7 on 2023-02-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_description',
            field=models.CharField(max_length=255),
        ),
    ]
